export interface AITool {
    id: string;
    name: string;
    url: string;
    category: string;
  }
  
  export const aiTools: AITool[] = [
    // Research (10 tools)
    { id: "1", name: "Perplexity AI", url: "https://perplexity.ai", category: "Research" },
    { id: "2", name: "DeepSeek", url: "https://deepseek.com", category: "Research" },
    { id: "3", name: "Elicit", url: "https://elicit.org", category: "Research" },
    { id: "4", name: "Consensus", url: "https://consensus.app", category: "Research" },
    { id: "5", name: "Scite", url: "https://scite.ai", category: "Research" },
    { id: "6", name: "ResearchRabbit", url: "https://researchrabbit.ai", category: "Research" },
    { id: "7", name: "Connected Papers", url: "https://connectedpapers.com", category: "Research" },
    { id: "8", name: "Litmaps", url: "https://litmaps.co", category: "Research" },
    { id: "9", name: "Semantic Scholar", url: "https://semanticscholar.org", category: "Research" },
    { id: "10", name: "Google Scholar", url: "https://scholar.google.com", category: "Research" },
    // Image Generation (10 tools)
    { id: "11", name: "Midjourney", url: "https://midjourney.com", category: "Image Generation" },
    { id: "12", name: "DALL-E 3", url: "https://openai.com/dall-e-3", category: "Image Generation" },
    { id: "13", name: "Stable Diffusion", url: "https://stability.ai", category: "Image Generation" },
    { id: "14", name: "Runway ML", url: "https://runwayml.com", category: "Image Generation" },
    { id: "15", name: "Artbreeder", url: "https://artbreeder.com", category: "Image Generation" },
    { id: "16", name: "NightCafe", url: "https://nightcafe.studio", category: "Image Generation" },
    { id: "17", name: "Vq-Vae-2", url: "https://deepmind.com", category: "Image Generation" },
    { id: "18", name: "Craiyon", url: "https://craiyon.com", category: "Image Generation" },
    { id: "19", name: "Logo Diffusion", url: "https://logodiffusion.com", category: "Image Generation" },
    { id: "20", name: "Stockimg AI", url: "https://stockimg.ai", category: "Image Generation" },
    // Copywriting (10 tools)
    { id: "21", name: "Jasper AI", url: "https://jasper.ai", category: "Copywriting" },
    { id: "22", name: "Copy.ai", url: "https://copy.ai", category: "Copywriting" },
    { id: "23", name: "Anyword", url: "https://anyword.com", category: "Copywriting" },
    { id: "24", name: "Writesonic", url: "https://writesonic.com", category: "Copywriting" },
    { id: "25", name: "Rytr", url: "https://rytr.me", category: "Copywriting" },
    { id: "26", name: "LongShot AI", url: "https://longshot.ai", category: "Copywriting" },
    { id: "27", name: "Neuraltext", url: "https://neuraltext.com", category: "Copywriting" },
    { id: "28", name: "AI-Writer", url: "https://ai-writer.com", category: "Copywriting" },
    { id: "29", name: "Simplified", url: "https://simplified.com", category: "Copywriting" },
    { id: "30", name: "Peppertype.ai", url: "https://peppertype.ai", category: "Copywriting" },
    // Writing (10 tools)
    { id: "31", name: "Grammarly", url: "https://grammarly.com", category: "Writing" },
    { id: "32", name: "ProWritingAid", url: "https://prowritingaid.com", category: "Writing" },
    { id: "33", name: "Hemingway Editor", url: "https://hemingwayapp.com", category: "Writing" },
    { id: "34", name: "Sudowrite", url: "https://sudowrite.com", category: "Writing" },
    { id: "35", name: "NovelAI", url: "https://novelai.net", category: "Writing" },
    { id: "36", name: "HyperWrite", url: "https://hyperwriteai.com", category: "Writing" },
    { id: "37", name: "QuillBot", url: "https://quillbot.com", category: "Writing" },
    { id: "38", name: "Wordtune", url: "https://wordtune.com", category: "Writing" },
    { id: "39", name: "INK Editor", url: "https://inkforall.com", category: "Writing" },
    { id: "40", name: "BetterWriter", url: "https://betterwriter.ai", category: "Writing" },
    // Presentation (10 tools)
    { id: "41", name: "Beautiful.ai", url: "https://beautiful.ai", category: "Presentation" },
    { id: "42", name: "SlidesAI", url: "https://slidesai.io", category: "Presentation" },
    { id: "43", name: "Tome", url: "https://tome.app", category: "Presentation" },
    { id: "44", name: "Pitch", url: "https://pitch.com", category: "Presentation" },
    { id: "45", name: "Canva", url: "https://canva.com", category: "Presentation" },
    { id: "46", name: "Prezi", url: "https://prezi.com", category: "Presentation" },
    { id: "47", name: "Visme", url: "https://visme.co", category: "Presentation" },
    { id: "48", name: "Decktopus", url: "https://decktopus.com", category: "Presentation" },
    { id: "49", name: "Zoho Show", url: "https://zoho.com/show", category: "Presentation" },
    { id: "50", name: "Emaze", url: "https://emaze.com", category: "Presentation" },
    // Video (10 tools)
    { id: "51", name: "Synthesia", url: "https://synthesia.io", category: "Video" },
    { id: "52", name: "Runway", url: "https://runwayml.com", category: "Video" },
    { id: "53", name: "Descript", url: "https://descript.com", category: "Video" },
    { id: "54", name: "Pictory", url: "https://pictory.ai", category: "Video" },
    { id: "55", name: "VEED", url: "https://veed.io", category: "Video" },
    { id: "56", name: "InVideo", url: "https://invideo.io", category: "Video" },
    { id: "57", name: "Topview", url: "https://topview.ai", category: "Video" },
    { id: "58", name: "Kapwing", url: "https://kapwing.com", category: "Video" },
    { id: "59", name: "FlexClip", url: "https://flexclip.com", category: "Video" },
    { id: "60", name: "Lumen5", url: "https://lumen5.com", category: "Video" },
    // Audio (10 tools)
    { id: "61", name: "Murf.ai", url: "https://murf.ai", category: "Audio" },
    { id: "62", name: "Adobe Podcast", url: "https://podcast.adobe.com", category: "Audio" },
    { id: "63", name: "Cleanvoice", url: "https://cleanvoice.ai", category: "Audio" },
    { id: "64", name: "Krisp", url: "https://krisp.ai", category: "Audio" },
    { id: "65", name: "Mubert", url: "https://mubert.com", category: "Audio" },
    { id: "66", name: "AssemblyAI", url: "https://assemblyai.com", category: "Audio" },
    { id: "67", name: "Resemble AI", url: "https://resemble.ai", category: "Audio" },
    { id: "68", name: "Voicemod", url: "https://voicemod.net", category: "Audio" },
    { id: "69", name: "WellSaid Labs", url: "https://wellsaidlabs.com", category: "Audio" },
    { id: "70", name: "Speechelo", url: "https://speechelo.com", category: "Audio" },
    // SEO (10 tools)
    { id: "71", name: "SurferSEO", url: "https://surferseo.com", category: "SEO" },
    { id: "72", name: "Ahrefs", url: "https://ahrefs.com", category: "SEO" },
    { id: "73", name: "SEMRush", url: "https://semrush.com", category: "SEO" },
    { id: "74", name: "Moz", url: "https://moz.com", category: "SEO" },
    { id: "75", name: "Yoast SEO", url: "https://yoast.com", category: "SEO" },
    { id: "76", name: "Quattr", url: "https://quattr.com", category: "SEO" },
    { id: "77", name: "KeywordSearch", url: "https://keywordsearch.com", category: "SEO" },
    { id: "78", name: "RankMath", url: "https://rankmath.com", category: "SEO" },
    { id: "79", name: "Mangools", url: "https://mangools.com", category: "SEO" },
    { id: "80", name: "Screaming Frog", url: "https://screamingfrog.co.uk", category: "SEO" },
    // Design (10 tools)
    { id: "81", name: "uBrand", url: "https://ubrand.com", category: "Design" },
    { id: "82", name: "Looka", url: "https://looka.com", category: "Design" },
    { id: "83", name: "Uizard", url: "https://uizard.io", category: "Design" },
    { id: "84", name: "Designs.AI", url: "https://designs.ai", category: "Design" },
    { id: "85", name: "Figma AI", url: "https://figma.com", category: "Design" },
    { id: "86", name: "Adobe Sensei", url: "https://adobe.com/sensei", category: "Design" },
    { id: "87", name: "Blimey", url: "https://blimeycreate.com", category: "Design" },
    { id: "88", name: "Brandmark", url: "https://brandmark.io", category: "Design" },
    { id: "89", name: "Hatchful", url: "https://hatchful.shopify.com", category: "Design" },
    { id: "90", name: "LogoMakr", url: "https://logomakr.com", category: "Design" },
    // Productivity (10 tools)
    { id: "91", name: "Taskade", url: "https://taskade.com", category: "Productivity" },
    { id: "92", name: "Notion AI", url: "https://notion.so", category: "Productivity" },
    { id: "93", name: "ClickUp AI", url: "https://clickup.com", category: "Productivity" },
    { id: "94", name: "Trello AI", url: "https://trello.com", category: "Productivity" },
    { id: "95", name: "Asana AI", url: "https://asana.com", category: "Productivity" },
    { id: "96", name: "Monday.com AI", url: "https://monday.com", category: "Productivity" },
    { id: "97", name: "Zapier AI", url: "https://zapier.com", category: "Productivity" },
    { id: "98", name: "Otter.ai", url: "https://otter.ai", category: "Productivity" },
    { id: "99", name: "Coda AI", url: "https://coda.io", category: "Productivity" },
    { id: "100", name: "Superhuman", url: "https://superhuman.com", category: "Productivity" },
    // Coding (10 tools)
    { id: "101", name: "GitHub Copilot", url: "https://github.com/features/copilot", category: "Coding" },
    { id: "102", name: "Tabnine", url: "https://tabnine.com", category: "Coding" },
    { id: "103", name: "Replit", url: "https://replit.com", category: "Coding" },
    { id: "104", name: "Codeium", url: "https://codeium.com", category: "Coding" },
    { id: "105", name: "CodiumAI", url: "https://codium.ai", category: "Coding" },
    { id: "106", name: "Blackbox AI", url: "https://blackbox.ai", category: "Coding" },
    { id: "107", name: "DeepCode", url: "https://deepcode.ai", category: "Coding" },
    { id: "108", name: "Kite", url: "https://kite.com", category: "Coding" },
    { id: "109", name: "Cursor", url: "https://cursor.sh", category: "Coding" },
    { id: "110", name: "Sourcegraph", url: "https://sourcegraph.com", category: "Coding" },
    // Learning (10 tools)
    { id: "111", name: "Khan Academy", url: "https://khanacademy.org", category: "Learning" },
    { id: "112", name: "Coursera", url: "https://coursera.org", category: "Learning" },
    { id: "113", name: "Duolingo", url: "https://duolingo.com", category: "Learning" },
    { id: "114", name: "Quizlet", url: "https://quizlet.com", category: "Learning" },
    { id: "115", name: "EdX", url: "https://edx.org", category: "Learning" },
    { id: "116", name: "Brilliant", url: "https://brilliant.org", category: "Learning" },
    { id: "117", name: "Socratic", url: "https://socratic.org", category: "Learning" },
    { id: "118", name: "Wolfram Alpha", url: "https://wolframalpha.com", category: "Learning" },
    { id: "119", name: "Skillshare", url: "https://skillshare.com", category: "Learning" },
    { id: "120", name: "Memrise", url: "https://memrise.com", category: "Learning" },
    // Background Removal (10 tools)
    { id: "121", name: "Erase.bg", url: "https://erase.bg", category: "Background Removal" },
    { id: "122", name: "Remove.bg", url: "https://remove.bg", category: "Background Removal" },
    { id: "123", name: "BGremover", url: "https://vanceai.com/background-remover", category: "Background Removal" },
    { id: "124", name: "Clipping Magic", url: "https://clippingmagic.com", category: "Background Removal" },
    { id: "125", name: "PhotoScissors", url: "https://photoscissors.com", category: "Background Removal" },
    { id: "126", name: "Slazzer", url: "https://slazzer.com", category: "Background Removal" },
    { id: "127", name: "Pixlr BG Removal", url: "https://pixlr.com/remove-background", category: "Background Removal" },
    { id: "128", name: "FocoClipping", url: "https://fococlipping.com", category: "Background Removal" },
    { id: "129", name: "Cutout.Pro", url: "https://cutout.pro", category: "Background Removal" },
    { id: "130", name: "Adobe Express BG Remover", url: "https://adobe.com/express/feature/image/remove-background", category: "Background Removal" },
    // Passport Size Photo Maker (10 tools)
    { id: "131", name: "AiPassportPhotos", url: "https://aipassportphotos.com", category: "Passport Size Photo Maker" },
    { id: "132", name: "Picsman", url: "https://picsman.ai", category: "Passport Size Photo Maker" },
    { id: "133", name: "Passportmaker", url: "https://passportmaker.com", category: "Passport Size Photo Maker" },
    { id: "134", name: "PhotoGov", url: "https://photogov.net", category: "Passport Size Photo Maker" },
    { id: "135", name: "insMind", url: "https://insmind.com", category: "Passport Size Photo Maker" },
    { id: "136", name: "AI Ease", url: "https://aiease.ai", category: "Passport Size Photo Maker" },
    { id: "137", name: "Supawork", url: "https://supawork.ai", category: "Passport Size Photo Maker" },
    { id: "138", name: "Remaker.ai", url: "https://remaker.ai", category: "Passport Size Photo Maker" },
    { id: "139", name: "PhotoAiD", url: "https://photoaid.com", category: "Passport Size Photo Maker" },
    { id: "140", name: "Snap2Pass", url: "https://snap2pass.com", category: "Passport Size Photo Maker" },
    // Resume Maker (10 tools)
    { id: "141", name: "Rezi", url: "https://rezi.ai", category: "Resume Maker" },
    { id: "142", name: "Kickresume", url: "https://kickresume.com", category: "Resume Maker" },
    { id: "143", name: "Enhancv", url: "https://enhancv.com", category: "Resume Maker" },
    { id: "144", name: "TealHQ", url: "https://tealhq.com", category: "Resume Maker" },
    { id: "145", name: "Canva Resume Builder", url: "https://canva.com/create/resumes", category: "Resume Maker" },
    { id: "146", name: "Resumaker.ai", url: "https://resumaker.ai", category: "Resume Maker" },
    { id: "147", name: "MyPerfectResume", url: "https://myperfectresume.com", category: "Resume Maker" },
    { id: "148", name: "Novoresume", url: "https://novoresume.com", category: "Resume Maker" },
    { id: "149", name: "Zety", url: "https://zety.com", category: "Resume Maker" },
    { id: "150", name: "Resume.io", url: "https://resume.io", category: "Resume Maker" },
    // Job Assistance (10 tools)
    { id: "151", name: "LinkedIn Job Search", url: "https://linkedin.com/jobs", category: "Job Assistance" },
    { id: "152", name: "Indeed AI", url: "https://indeed.com", category: "Job Assistance" },
    { id: "153", name: "Glassdoor", url: "https://glassdoor.com", category: "Job Assistance" },
    { id: "154", name: "The Muse", url: "https://themuse.com", category: "Job Assistance" },
    { id: "155", name: "Hiration", url: "https://hiration.com", category: "Job Assistance" },
    { id: "156", name: "Jobscan", url: "https://jobscan.co", category: "Job Assistance" },
    { id: "157", name: "CareerBuilder AI", url: "https://careerbuilder.com", category: "Job Assistance" },
    { id: "158", name: "Yoodli", url: "https://yoodli.ai", category: "Job Assistance" },
    { id: "159", name: "Big Interview", url: "https://biginterview.com", category: "Job Assistance" },
    { id: "160", name: "ResumeWorded", url: "https://resumeworded.com", category: "Job Assistance" },
    // Automation (10 tools)
    { id: "161", name: "Zapier", url: "https://zapier.com", category: "Automation" },
    { id: "162", name: "Make", url: "https://make.com", category: "Automation" },
    { id: "163", name: "IFTTT", url: "https://ifttt.com", category: "Automation" },
    { id: "164", name: "Automate.io", url: "https://automate.io", category: "Automation" },
    { id: "165", name: "N8n", url: "https://n8n.io", category: "Automation" },
    { id: "166", name: "Tray.io", url: "https://tray.io", category: "Automation" },
    { id: "167", name: "Workato", url: "https://workato.com", category: "Automation" },
    { id: "168", name: "Parabola", url: "https://parabola.io", category: "Automation" },
    { id: "169", name: "Integromat", url: "https://integromat.com", category: "Automation" },
    { id: "170", name: "Bubble", url: "https://bubble.io", category: "Automation" },
    // Chatbots (10 tools)
    { id: "171", name: "ChatGPT", url: "https://chat.openai.com", category: "Chatbots" },
    { id: "172", name: "Claude", url: "https://anthropic.com", category: "Chatbots" },
    { id: "173", name: "Grok", url: "https://x.ai/grok", category: "Chatbots" },
    { id: "174", name: "Dialogflow", url: "https://cloud.google.com/dialogflow", category: "Chatbots" },
    { id: "175", name: "Botpress", url: "https://botpress.com", category: "Chatbots" },
    { id: "176", name: "Tidio", url: "https://tidio.com", category: "Chatbots" },
    { id: "177", name: "ManyChat", url: "https://manychat.com", category: "Chatbots" },
    { id: "178", name: "Landbot", url: "https://landbot.io", category: "Chatbots" },
    { id: "179", name: "Drift", url: "https://drift.com", category: "Chatbots" },
    { id: "180", name: "Intercom", url: "https://intercom.com", category: "Chatbots" },
    // Data Analysis (10 tools)
    { id: "181", name: "Tableau AI", url: "https://tableau.com", category: "Data Analysis" },
    { id: "182", name: "Power BI AI", url: "https://powerbi.microsoft.com", category: "Data Analysis" },
    { id: "183", name: "Looker Studio", url: "https://lookerstudio.google.com", category: "Data Analysis" },
    { id: "184", name: "DataRobot", url: "https://datarobot.com", category: "Data Analysis" },
    { id: "185", name: "RapidMiner", url: "https://rapidminer.com", category: "Data Analysis" },
    { id: "186", name: "KNIME", url: "https://knime.com", category: "Data Analysis" },
    { id: "187", name: "Alteryx", url: "https://alteryx.com", category: "Data Analysis" },
    { id: "188", name: "Qlik Sense", url: "https://qlik.com", category: "Data Analysis" },
    { id: "189", name: "Sisense", url: "https://sisense.com", category: "Data Analysis" },
    { id: "190", name: "ThoughtSpot", url: "https://thoughtspot.com", category: "Data Analysis" },
    // Text-to-Speech (10 tools)
    { id: "191", name: "ElevenLabs", url: "https://elevenlabs.io", category: "Text-to-Speech" },
    { id: "192", name: "Speechify", url: "https://speechify.com", category: "Text-to-Speech" },
    { id: "193", name: "Descript", url: "https://descript.com", category: "Text-to-Speech" },
    { id: "194", name: "Synthesia", url: "https://synthesia.io", category: "Text-to-Speech" },
    { id: "195", name: "WellSaid Labs", url: "https://wellsaidlabs.com", category: "Text-to-Speech" },
    { id: "196", name: "Resemble AI", url: "https://resemble.ai", category: "Text-to-Speech" },
    { id: "197", name: "Voicemod", url: "https://voicemod.net", category: "Text-to-Speech" },
    { id: "198", name: "Play.ht", url: "https://play.ht", category: "Text-to-Speech" },
    { id: "199", name: "Speechelo", url: "https://speechelo.com", category: "Text-to-Speech" },
    { id: "200", name: "Murf.ai", url: "https://murf.ai", category: "Text-to-Speech" }
  ];